version: '3.9'

services:
  asset_db:
    image: postgres:latest
    container_name: asset_db
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres-asset:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=asset_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  assets:
    build:
      context: ../  # Uses the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - asset_db
    restart: unless-stopped