version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: asset_db
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres-asset:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=asset_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
